#! /bin/bash

echo
echo Deploying ...
echo
pushd $BF

bfbuild

docker build -t bigfractal/tangle .
docker build --platform linux/amd64 -t bigfractal/tangle:amd64 .

docker push bigfractal/tangle
docker push bigfractal/tangle:amd64

ssh tanglebox docker pull bigfractal/tangle:amd64
ssh tanglebox docker-compose down
ssh tanglebox docker-compose up

popd